export const mockLeads = [
  {
    id: '1',
    name: 'João Silva',
    status: 'Novo',
    date: '2023-10-25',
    interest: 'Alto',
    email: 'joao@example.com',
    phone: '(11) 99999-1111',
    notes: 'Interessado na linha Reserva.',
  },
  {
    id: '2',
    name: 'Maria Fernandes',
    status: 'Em Contato',
    date: '2023-10-24',
    interest: 'Médio',
    email: 'maria@example.com',
    phone: '(21) 98888-2222',
    notes: 'Aguardando retorno sobre degustação.',
  },
  {
    id: '3',
    name: 'Carlos Santos',
    status: 'Negociando',
    date: '2023-10-20',
    interest: 'Alto',
    email: 'carlos@example.com',
    phone: '(31) 97777-3333',
    notes: 'Quer fechar plano anual Gold.',
  },
  {
    id: '4',
    name: 'Ana Costa',
    status: 'Ganho',
    date: '2023-10-15',
    interest: 'Alto',
    email: 'ana@example.com',
    phone: '(41) 96666-4444',
    notes: 'Convertida para ALA Private.',
  },
  {
    id: '5',
    name: 'Pedro Alves',
    status: 'Perdido',
    date: '2023-10-10',
    interest: 'Baixo',
    email: 'pedro@example.com',
    phone: '(51) 95555-5555',
    notes: 'Achou o valor alto no momento.',
  },
]

export const mockMembers = [
  {
    id: '1',
    name: 'Roberto Almeida',
    tier: 'Reserva',
    joinedAt: '2021-05-12',
    cellarValue: 'R$ 15.400',
    nextAllocation: 'Novembro 2023',
  },
  {
    id: '2',
    name: 'Juliana Paes',
    tier: 'Ouro',
    joinedAt: '2022-08-03',
    cellarValue: 'R$ 8.200',
    nextAllocation: 'Dezembro 2023',
  },
  {
    id: '3',
    name: 'Fernando Costa',
    tier: 'Prata',
    joinedAt: '2023-01-15',
    cellarValue: 'R$ 3.500',
    nextAllocation: 'Outubro 2023',
  },
  {
    id: '4',
    name: 'Camila Rocha',
    tier: 'Bronze',
    joinedAt: '2023-06-20',
    cellarValue: 'R$ 1.200',
    nextAllocation: 'Novembro 2023',
  },
  {
    id: '5',
    name: 'Marcos Lima',
    tier: 'Reserva',
    joinedAt: '2019-11-10',
    cellarValue: 'R$ 25.000',
    nextAllocation: 'Novembro 2023',
  },
]

export const mockInventory = [
  {
    id: '1',
    name: 'Casa Rosada Gran Reserva',
    vintage: '2018',
    type: 'Tinto',
    stock: 45,
    exclusive: true,
    img: 'https://img.usecurling.com/p/200/300?q=red%20wine%20bottle&color=red',
  },
  {
    id: '2',
    name: 'Casa Rosada Chardonnay',
    vintage: '2021',
    type: 'Branco',
    stock: 120,
    exclusive: false,
    img: 'https://img.usecurling.com/p/200/300?q=white%20wine%20bottle&color=yellow',
  },
  {
    id: '3',
    name: 'ALA Private Rosé',
    vintage: '2022',
    type: 'Rosé',
    stock: 15,
    exclusive: true,
    img: 'https://img.usecurling.com/p/200/300?q=rose%20wine%20bottle&color=pink',
  },
  {
    id: '4',
    name: 'Syrah de Terroir',
    vintage: '2019',
    type: 'Tinto',
    stock: 60,
    exclusive: false,
    img: 'https://img.usecurling.com/p/200/300?q=wine%20bottle&color=purple',
  },
  {
    id: '5',
    name: 'Pinot Noir Edição Limitada',
    vintage: '2020',
    type: 'Tinto',
    stock: 5,
    exclusive: true,
    img: 'https://img.usecurling.com/p/200/300?q=premium%20wine%20bottle&color=black',
  },
]

export const mockChartData = [
  { month: 'Jan', members: 120, revenue: 15000 },
  { month: 'Fev', members: 135, revenue: 18000 },
  { month: 'Mar', members: 150, revenue: 22000 },
  { month: 'Abr', members: 180, revenue: 26000 },
  { month: 'Mai', members: 210, revenue: 31000 },
  { month: 'Jun', members: 250, revenue: 38000 },
]

export const mockActivities = [
  { id: '1', user: 'Roberto A.', action: 'resgatou a cota mensal', time: 'Há 2 horas' },
  { id: '2', user: 'Juliana P.', action: 'atualizou o plano para Ouro', time: 'Há 5 horas' },
  { id: '3', user: 'Carlos S.', action: 'entrou como novo lead', time: 'Ontem' },
]
